// lib/components/Sidebar.tsx
import React from "react";
import IconButton from "./IconButton";
import Logo from "./Logo";

const Sidebar = () => {
  return (
    <div className="w-[68px] h-full p-2 space-y-2">
      <div className="aspect-square flex justify-center items-center p-2.5">
        <Logo />
      </div>
      <div className="space-y-2 p-0.5">
        <IconButton variant="nav" icon="home" />
        <IconButton variant="nav" icon="browse" />
        <IconButton variant="nav" icon="bookmarks" />
        <IconButton variant="nav" icon="browse" />
      </div>
    </div>
  );
};

export default Sidebar;

// src/lib/components/SideBar.svelte
<script>
	import logo from '$lib/assets/logo.svg';
	import IconButton from './IconButton.svelte';
	import homeIcon from '$lib/icons/homeIcon.svelte';
	import browseIcon from '$lib/icons/browseIcon.svelte';
	import bookmarksIcon from '$lib/icons/bookmarksIcon.svelte';
</script>

<div class="w-[68px] h-full p-2 space-y-2">
	<div class="aspect-square flex justify-center items-center p-2.5">
		<img class="h-full w-full" src={logo} alt="" />
	</div>
	<div class="space-y-2 p-0.5">
		<IconButton variant="nav" icon={homeIcon} />
		<IconButton variant="nav" icon={browseIcon} />
		<IconButton variant="nav" icon={bookmarksIcon} />
		<IconButton variant="nav" icon={browseIcon} />
	</div>
</div>
